### ISSUE TITLE
Error running project with spring-boot-devtools dependency

### ISSUE THREAD

**Issue by AndreasZaschka** [st-tu-dresden/videoshop#44]
Same as https://github.com/st-tu-dresden/kickstart/issues/14

**Comment by AndreasZaschka** [comment]
Same as https://github.com/st-tu-dresden/kickstart/issues/14

**Comment by olivergierke** [comment]
Removed for now see @st-tu-dresden/kickstart#14 for details.

I think we don't need to dive into tagging issues that deeply. That help is requested if a bug is reported is pretty obvious. Also, we're not really flooded in tickets so that I guess we don't need to mark blockers explicitly. I guess the most important tag is in-progress to make sure nobody else is starting to work on the issue and we overlap work.
